language: node_js
node_js:
- '4'
deploy:
  provider: heroku
  api_key:
    secure: btrDYyKapICRNNag72jSuHhi6KC9J0WWm8RaQvmnbhHT2uYKEm6hu8lLrmo4sgix830aAxxrAERTSGmy/Tw8tyi9iXaRIHSkt7Zvjuzs1j01vI5/UklJV0b0VPh5faoAZ/NIJ7xemtIKRlCKQB4OrqgkUHXdAANAR+QIweaADWWo9XHImyr6iCF3xbDiiYfwHQmlFuEEt8xZo7zg+8/Uxam2K+9YdgGrKEs51LV+FFRog2wodrLLdSBx4524jgN76pcc8MdHbJshzxITTPNgKKo0fcyPBAHq2cTDw4E8HjnNdJNnqUJZFxvrCHM/PYVBjK+pLYZkuCNuOWEDdTs6674Bdfvn8D/dZUVv5K7Wi2RnwhLX2oXJ+PKdtl4qv/pWHcYYEWuKxc/812V5UoTeBcNcVMZWCJYwG6XP0y7Lr0DpOgLm0JXfaUSakXNuXJFY6UzooHrmN+oaH4BBFswX9lp7xSBe28b+0MEKmlqOU4IZYlcvrFwOVc2niLi+DNsR2hVv+XzhUeJTjYVpEG/sm8khy/YJ7+4AbggjLSc5og05pJdHrXe1ncFFPLxZE0l8VSZywtFbrXRl02tfbPypx7cHZFoQAAHpYS4r9X7dsxWzENcvOQyxinR+igDHxsYZcunUppS4hIRfsRDhkvbrj9h2frBthzuTAXkTBnPHCQ8=
  app: legends-of-pong
